### ISSUE TITLE
can antenna separation be changed?

### ISSUE THREAD

**Issue by albinwwells** [btobers/NOSEpick#7]

**Comment by btobers** [comment]
Added user-defined antenna separation option to configuration file.

Note, the config.ini file is initialized the first time ragu is run on a computer, so if you've previously run ragu, you'll need to do one of three things to implement this change:
1. add the following two lines directly under the 'output' key
```
# float asep: antenna separation in meters (optional)
asep = 
```
2. Regenerate your config file 
```
import os
from ragu import config
# get configuration file
basedir = os.path.join(os.path.expanduser('~'),'RAGU')
config.create_config(basedir+'/config.ini')
```
3. Remove your existing configuration file, and then a new one will be generated upon running ragu
